### ISSUE TITLE
Review Team of Two

### ISSUE THREAD

**Issue by marijanbrvar** [pasytchangwa/React_ReduxGrpPro#26]
We are a group of two.
(Repo link)[https://github.com/pasytchangwa/React_ReduxGrpPro]

**Comment by arslanbisharat** [comment]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [x] In GitHub issues, you should provide us the following info.

- link to their GitHub project
- information about the number of people in their group
- [x] The distribution of cards is unequal. Please make sure cards are distributed properly. 

While you have link but didn't make it link properly. And you didn't add names and github handles of the students.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by marijanbrvar** [comment]
Link to their GitHub project: [React_ReduxGrpPro](https://github.com/pasytchangwa/React_ReduxGrpPro)
Information about the number of people: Two (2) [Sylvestre Tc Pagkeu](https://github.com/pasytchangwa) &  [Marijan Brvar](https://github.com/marijanbrvar)

**Comment by AshakaE** [comment]
### Hi Team 🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
